/* function yourApp(){alert('your UI code here!')} */

function podcastShare (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/podcastShare';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function podcastReadHash (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/podcastReadHash';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function podcastRead (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/podcastRead';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function podcastAudio (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/podcastAudio';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function podcastAudioCorto (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/podcastAudioCorto';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function readLengthPodcastAudio (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/readLengthPodcastAudio';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function readPodcastAudioMain (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/readPodcastAudioMain';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function readPodcastAudio (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/readPodcastAudio';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
function createCathegoriesDefault (message) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/createCathegoriesDefault';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {}};xhr.send(message);}
function readCathegories (message, callback) {var xhr = new XMLHttpRequest ();var url = '/fn/podcast/readCathegories';xhr.open('POST',url,true);xhr.setRequestHeader('Content-type','application/json');xhr.onreadystatechange = function () {if (xhr.readyState === 4 && xhr.status === 200 ) {callback(xhr.responseText);}};xhr.send(message);}
